COMMENT ON TABLE SAMPLE IS '샘플 정보';
COMMENT ON COLUMN SAMPLE.ID IS '샘플 ID';
COMMENT ON COLUMN SAMPLE.NAME IS '이름';
COMMENT ON COLUMN SAMPLE.DESCRIPTION IS '설명';
COMMENT ON COLUMN SAMPLE.USE_YN IS '사용 여부';
COMMENT ON COLUMN SAMPLE.REG_USER IS '등록 사용자';
COMMENT ON TABLE IDS IS 'ID 채번 정보';
COMMENT ON COLUMN IDS.TABLE_NAME IS '테이블명';
COMMENT ON COLUMN IDS.NEXT_ID IS '다음 ID';
