CREATE TABLE SAMPLE (
    ID          VARCHAR2(16)  NOT NULL,
    NAME        VARCHAR2(50),
    DESCRIPTION VARCHAR2(200),
    USE_YN      CHAR(1),
    REG_USER    VARCHAR2(10),
    CONSTRAINT PK_SAMPLE PRIMARY KEY (ID)
);

CREATE TABLE IDS (
    TABLE_NAME VARCHAR2(16) NOT NULL,
    NEXT_ID    NUMBER(30)   NOT NULL,
    CONSTRAINT PK_IDS PRIMARY KEY (TABLE_NAME)
);
