ALTER TABLE SAMPLE COMMENT = '샘플 정보';
ALTER TABLE SAMPLE
    MODIFY ID VARCHAR(16) NOT NULL COMMENT '샘플 ID',
    MODIFY NAME VARCHAR(50) COMMENT '이름',
    MODIFY DESCRIPTION VARCHAR(200) COMMENT '설명',
    MODIFY USE_YN CHAR(1) COMMENT '사용 여부',
    MODIFY REG_USER VARCHAR(10) COMMENT '등록 사용자';
ALTER TABLE IDS COMMENT = 'ID 채번 정보';
ALTER TABLE IDS
    MODIFY TABLE_NAME VARCHAR(16) NOT NULL COMMENT '테이블명',
    MODIFY NEXT_ID DECIMAL(30) NOT NULL COMMENT '다음 ID';
