CREATE TABLE SAMPLE (
    ID          VARCHAR(16)  NOT NULL,
    NAME        VARCHAR(50),
    DESCRIPTION VARCHAR(200),
    USE_YN      CHAR(1),
    REG_USER    VARCHAR(10),
    CONSTRAINT PK_SAMPLE PRIMARY KEY (ID)
);

CREATE TABLE IDS (
    TABLE_NAME VARCHAR(16) NOT NULL,
    NEXT_ID    NUMERIC(30) NOT NULL,
    CONSTRAINT PK_IDS PRIMARY KEY (TABLE_NAME)
);
